### ISSUE TITLE
Breaks 'open_url' command shipped with Sublime Text

### ISSUE THREAD

**Issue by nsubiron** [NoxArt/SublimeText2-LinkOpener#5]
Sublime Text already has a command called 'open_url' that accepts a keyword argument 'url', when called it is redirected to LinkOpener.OpenUrlCommand that doesn't expect the extra argument

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 545, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'url'
```

E.g., Help>Documentation is not working anymore (at least on Sublime Text 3 for Windows)

**Comment by cvladan** [comment]
Can you please update documentation (README) accordingly.

**Comment by NoxArt** [comment]
Fixed, thank you!
